### ISSUE TITLE
Supporting blog post cannot be reached

### ISSUE THREAD

**Issue by mwebber** [pfertyk/webrtc-working-example#1]
It looks like https://pfertyk.me/ cannot be reached; the DNS does not resolve (for me, anyhow).

**Comment by pfertyk** [comment]
Hi! Thank you for reporting this. I was able to reach it from my machine on 2 different browsers, 2 of my friends also opened the link without problems. It seems there is a problem with network connection on your side, unfortunately :(

However, this issue made me realize that the blog post link used HTTP instead of HTTPS (my blog doesn't force HTTPS). I've fixed it. Thanks for pointing it out!

**Comment by mwebber** [comment]
Apologies for the false alarm. Before i opened the issue, I did try downdetector (or one of those) which also reported probems. Anyhow, working for me now, so closing.
