### ISSUE TITLE
Does not appear to work

### ISSUE THREAD

**Issue by shurik** [pfertyk/webrtc-working-example#8]
Hello,

Thank you for the blog post and this repo. I've tried to follow the post and tried using this repo with docker-compose. Unfortunately in both cases I've ended up with a blank screen and errors in browser console like:

```
GET /socket.io/?EIO=3&transport=polling&t=NQn5egf 404
```

Seems like the JS script is attempting to access /socket.io/ on the Python socket server. I can't seem to figure out how or why.

**Comment by csik** [comment]
Hi Shurik, 

I had the same problem; I haven't done anything with the docker file but locally (not docker) in a python3.9 virtualenv I upgraded:
- aiohttp-3.7.3
- python-socketio-5.0.4

This gives me a blank firefox page asking for permissions; when I open another firefox page, then things seem to work. It would be great to fix the docker implementation, too.

**Comment by pfertyk** [comment]
Hi @shurik and @csik !

Thanks for reporting this issue. I believe I've found a solution. This example uses an old version of socket.io.js client, because React Native had some problems with newer versions. Possibly those problems have been solved already, but I didn't have the time to look into this, so for now I decided to stick to the old version. According to this comment on GitHub, that old version of socket.io client (2.x) requires Engine.IO version 3.x and python-socketio version 4.x:

https://github.com/miguelgrinberg/python-socketio/issues/578#issuecomment-740528415

However, python-socketio package has a newer dependency of python-engineio available, and if left unsupervised, will install 4.0.0. By specifying python-engineio version as 3.9.0 in signaling/requirements.txt this can be fixed:

```
aiohttp==3.6.2
python-socketio==4.5.0
python-engineio==3.9.0
```

This solved the issue on my machine. Could you confirm on yours?

**Comment by pfertyk** [comment]
There was a bit of inactivity regarding this task, so I merged the PR ;)
